import type { ThemeDefinition } from "./index";

export const darkTheme: ThemeDefinition = {
  id: "abyss-void",
  label: "Abyss Void",
  base: "dark",
  swatch: "#ff6b2b",
  css: {
    "--bg-void": "#080b10",
    "--bg-deep": "#0d1117",
    "--bg-panel": "#111620",
    "--bg-surface": "#161c2a",
    "--bg-elevated": "#1c2333",
    "--bg-hover": "#232d42",
    "--border-dim": "#1e2a3a",
    "--border-soft": "#253042",
    "--border-mid": "#2e3d54",
    "--text-primary": "#e2eaf5",
    "--text-secondary": "#7a90aa",
    "--text-muted": "#3f5068",
    "--text-dim": "#2a3a50",
    "--accent": "#ff6b2b",
    "--accent-glow": "rgba(255, 107, 43, 0.2)",
    "--accent-dim": "rgba(255, 107, 43, 0.08)",
    "--green": "#3ddc97",
    "--red": "#ff4d6a",
    "--yellow": "#ffd166",
    "--blue": "#5ba4f5",
    "--error-bg": "rgba(255, 77, 106, 0.06)",
    "--error-bg-hint": "rgba(255, 77, 106, 0.06)",
    "--error-border": "rgba(255, 77, 106, 0.25)",
    "--statusbar-text": "rgba(255, 255, 255, 0.9)",
    "--statusbar-text-dim": "rgba(255, 255, 255, 0.7)",
    "--statusbar-badge-bg": "rgba(0, 0, 0, 0.2)",
  },
  monaco: {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "keyword", foreground: "ff6b2b", fontStyle: "bold" },
      { token: "keyword.operator", foreground: "5ba4f5" },
      { token: "type", foreground: "3ddc97" },
      { token: "support.function", foreground: "ffd166" },
      { token: "constant", foreground: "c792ea" },
      { token: "string", foreground: "a8d8a8" },
      { token: "number", foreground: "79d4f1" },
      { token: "number.float", foreground: "79d4f1" },
      { token: "comment", foreground: "3f5068", fontStyle: "italic" },
      { token: "operator", foreground: "7a90aa" },
      { token: "identifier", foreground: "e2eaf5" },
      { token: "delimiter", foreground: "5b6d82" },
    ],
    colors: {
      "editor.background": "#0d1117",
      "editor.foreground": "#e2eaf5",
      "editor.lineHighlightBackground": "#161c2a",
      "editor.selectionBackground": "#253042",
      "editorLineNumber.foreground": "#2e3d54",
      "editorLineNumber.activeForeground": "#7a90aa",
      "editorGutter.background": "#0d1117",
      "editorCursor.foreground": "#ff6b2b",
      "editor.findMatchBackground": "#ff6b2b44",
      "editorHoverWidget.background": "#0d1117",
      "editorHoverWidget.border": "#f14c4c",
    },
  },
};
