import type { ThemeDefinition } from "./index";

export const catppuccinMochaTheme: ThemeDefinition = {
  id: "catppuccin-mocha",
  label: "Catppuccin Mocha",
  base: "dark",
  swatch: "#cba6f7",
  css: {
    "--bg-void": "#11111b",
    "--bg-deep": "#1e1e2e",
    "--bg-panel": "#181825",
    "--bg-surface": "#313244",
    "--bg-elevated": "#45475a",
    "--bg-hover": "#585b70",
    "--border-dim": "#2a2a3d",
    "--border-soft": "#313244",
    "--border-mid": "#45475a",
    "--text-primary": "#cdd6f4",
    "--text-secondary": "#bac2de",
    "--text-muted": "#6c7086",
    "--text-dim": "#45475a",
    "--accent": "#cba6f7",
    "--accent-glow": "rgba(203, 166, 247, 0.2)",
    "--accent-dim": "rgba(203, 166, 247, 0.08)",
    "--green": "#a6e3a1",
    "--red": "#f38ba8",
    "--yellow": "#f9e2af",
    "--blue": "#89b4fa",
    "--error-bg": "rgba(243, 139, 168, 0.06)",
    "--error-bg-hint": "rgba(243, 139, 168, 0.06)",
    "--error-border": "rgba(243, 139, 168, 0.25)",
    "--statusbar-text": "rgba(255, 255, 255, 0.9)",
    "--statusbar-text-dim": "rgba(255, 255, 255, 0.7)",
    "--statusbar-badge-bg": "rgba(0, 0, 0, 0.2)",
  },
  monaco: {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "keyword", foreground: "cba6f7", fontStyle: "bold" },
      { token: "keyword.operator", foreground: "89dceb" },
      { token: "type", foreground: "94e2d5" },
      { token: "support.function", foreground: "89b4fa" },
      { token: "constant", foreground: "fab387" },
      { token: "string", foreground: "a6e3a1" },
      { token: "number", foreground: "fab387" },
      { token: "number.float", foreground: "fab387" },
      { token: "comment", foreground: "6c7086", fontStyle: "italic" },
      { token: "operator", foreground: "89dceb" },
      { token: "identifier", foreground: "cdd6f4" },
      { token: "delimiter", foreground: "7f849c" },
    ],
    colors: {
      "editor.background": "#1e1e2e",
      "editor.foreground": "#cdd6f4",
      "editor.lineHighlightBackground": "#313244",
      "editor.selectionBackground": "#45475a",
      "editorLineNumber.foreground": "#45475a",
      "editorLineNumber.activeForeground": "#6c7086",
      "editorGutter.background": "#1e1e2e",
      "editorCursor.foreground": "#cba6f7",
      "editor.findMatchBackground": "#cba6f744",
      "editorHoverWidget.background": "#1e1e2e",
      "editorHoverWidget.border": "#f38ba8",
    },
  },
};
