import type { ThemeDefinition } from "./index";

export const catppuccinLatteTheme: ThemeDefinition = {
  id: "catppuccin-latte",
  label: "Catppuccin Latte",
  base: "light",
  swatch: "#8839ef",
  css: {
    "--bg-void": "#e6e9ef",
    "--bg-deep": "#eff1f5",
    "--bg-panel": "#e6e9ef",
    "--bg-surface": "#dce0e8",
    "--bg-elevated": "#ccd0da",
    "--bg-hover": "#bcc0cc",
    "--border-dim": "#ccd0da",
    "--border-soft": "#bcc0cc",
    "--border-mid": "#acb0be",
    "--text-primary": "#4c4f69",
    "--text-secondary": "#5c5f77",
    "--text-muted": "#6c6f85",
    "--text-dim": "#9ca0b0",
    "--accent": "#8839ef",
    "--accent-glow": "rgba(136, 57, 239, 0.18)",
    "--accent-dim": "rgba(136, 57, 239, 0.08)",
    "--green": "#40a02b",
    "--red": "#d20f39",
    "--yellow": "#df8e1d",
    "--blue": "#1e66f5",
    "--error-bg": "rgba(210, 15, 57, 0.06)",
    "--error-bg-hint": "rgba(210, 15, 57, 0.04)",
    "--error-border": "rgba(210, 15, 57, 0.25)",
    "--statusbar-text": "rgba(255, 255, 255, 0.95)",
    "--statusbar-text-dim": "rgba(255, 255, 255, 0.75)",
    "--statusbar-badge-bg": "rgba(0, 0, 0, 0.15)",
  },
  monaco: {
    base: "vs",
    inherit: true,
    rules: [
      { token: "keyword", foreground: "8839ef", fontStyle: "bold" },
      { token: "keyword.operator", foreground: "04a5e5" },
      { token: "type", foreground: "179299" },
      { token: "support.function", foreground: "209fb5" },
      { token: "constant", foreground: "fe640b" },
      { token: "string", foreground: "40a02b" },
      { token: "number", foreground: "fe640b" },
      { token: "number.float", foreground: "fe640b" },
      { token: "comment", foreground: "9ca0b0", fontStyle: "italic" },
      { token: "operator", foreground: "04a5e5" },
      { token: "identifier", foreground: "4c4f69" },
      { token: "delimiter", foreground: "6c6f85" },
    ],
    colors: {
      "editor.background": "#eff1f5",
      "editor.foreground": "#4c4f69",
      "editor.lineHighlightBackground": "#e6e9ef",
      "editor.selectionBackground": "#bcc0cc",
      "editorLineNumber.foreground": "#acb0be",
      "editorLineNumber.activeForeground": "#6c6f85",
      "editorGutter.background": "#eff1f5",
      "editorCursor.foreground": "#8839ef",
      "editor.findMatchBackground": "#8839ef44",
      "editorHoverWidget.background": "#e6e9ef",
      "editorHoverWidget.border": "#d20f39",
    },
  },
};
