import type { ThemeDefinition } from "./index";

export const gruvboxLightTheme: ThemeDefinition = {
  id: "gruvbox-light",
  label: "Gruvbox Light",
  base: "light",
  swatch: "#af3a03",
  css: {
    "--bg-void": "#f9f5d7",
    "--bg-deep": "#fbf1c7",
    "--bg-panel": "#f2e5bc",
    "--bg-surface": "#ebdbb2",
    "--bg-elevated": "#d5c4a1",
    "--bg-hover": "#bdae93",
    "--border-dim": "#ebdbb2",
    "--border-soft": "#d5c4a1",
    "--border-mid": "#bdae93",
    "--text-primary": "#3c3836",
    "--text-secondary": "#7c6f64",
    "--text-muted": "#a89984",
    "--text-dim": "#bdae93",
    "--accent": "#af3a03",
    "--accent-glow": "rgba(175, 58, 3, 0.18)",
    "--accent-dim": "rgba(175, 58, 3, 0.08)",
    "--green": "#79740e",
    "--red": "#9d0006",
    "--yellow": "#b57614",
    "--blue": "#076678",
    "--error-bg": "rgba(157, 0, 6, 0.06)",
    "--error-bg-hint": "rgba(157, 0, 6, 0.04)",
    "--error-border": "rgba(157, 0, 6, 0.25)",
    "--statusbar-text": "rgba(255, 255, 255, 0.95)",
    "--statusbar-text-dim": "rgba(255, 255, 255, 0.75)",
    "--statusbar-badge-bg": "rgba(0, 0, 0, 0.15)",
  },
  monaco: {
    base: "vs",
    inherit: true,
    rules: [
      { token: "keyword", foreground: "9d0006", fontStyle: "bold" },
      { token: "keyword.operator", foreground: "076678" },
      { token: "type", foreground: "427b58" },
      { token: "support.function", foreground: "b57614" },
      { token: "constant", foreground: "8f3f71" },
      { token: "string", foreground: "79740e" },
      { token: "number", foreground: "8f3f71" },
      { token: "number.float", foreground: "8f3f71" },
      { token: "comment", foreground: "928374", fontStyle: "italic" },
      { token: "operator", foreground: "7c6f64" },
      { token: "identifier", foreground: "3c3836" },
      { token: "delimiter", foreground: "7c6f64" },
    ],
    colors: {
      "editor.background": "#fbf1c7",
      "editor.foreground": "#3c3836",
      "editor.lineHighlightBackground": "#ebdbb2",
      "editor.selectionBackground": "#d5c4a1",
      "editorLineNumber.foreground": "#bdae93",
      "editorLineNumber.activeForeground": "#7c6f64",
      "editorGutter.background": "#fbf1c7",
      "editorCursor.foreground": "#af3a03",
      "editor.findMatchBackground": "#af3a0344",
      "editorHoverWidget.background": "#f2e5bc",
      "editorHoverWidget.border": "#bdae93",
    },
  },
};
