import type { ThemeDefinition } from "./index";

export const lightTheme: ThemeDefinition = {
  id: "mist",
  label: "Mist",
  base: "light",
  swatch: "#2878d0",
  css: {
    "--bg-void": "#e8ecf2",
    "--bg-deep": "#f0f4f8",
    "--bg-panel": "#e4e9f0",
    "--bg-surface": "#dde3ec",
    "--bg-elevated": "#d6dde8",
    "--bg-hover": "#cdd5e2",
    "--border-dim": "#c8d0dc",
    "--border-soft": "#bcc5d4",
    "--border-mid": "#a8b4c8",
    "--text-primary": "#1a2232",
    "--text-secondary": "#3a4f6a",
    "--text-muted": "#6a7f9a",
    "--text-dim": "#94a5b8",
    "--accent": "#2878d0",
    "--accent-glow": "rgba(40, 120, 208, 0.18)",
    "--accent-dim": "rgba(40, 120, 208, 0.08)",
    "--green": "#1a9e6a",
    "--red": "#d93050",
    "--yellow": "#c47f00",
    "--blue": "#2878d0",
    "--error-bg": "rgba(217, 48, 80, 0.06)",
    "--error-bg-hint": "rgba(217, 48, 80, 0.04)",
    "--error-border": "rgba(217, 48, 80, 0.25)",
    "--statusbar-text": "rgba(255, 255, 255, 0.95)",
    "--statusbar-text-dim": "rgba(255, 255, 255, 0.75)",
    "--statusbar-badge-bg": "rgba(0, 0, 0, 0.15)",
  },
  monaco: {
    base: "vs",
    inherit: true,
    rules: [
      { token: "keyword", foreground: "c04000", fontStyle: "bold" },
      { token: "keyword.operator", foreground: "1a6abf" },
      { token: "type", foreground: "0a7a50" },
      { token: "support.function", foreground: "8a6000" },
      { token: "constant", foreground: "7a00aa" },
      { token: "string", foreground: "1a7040" },
      { token: "number", foreground: "1a5abf" },
      { token: "number.float", foreground: "1a5abf" },
      { token: "comment", foreground: "8899aa", fontStyle: "italic" },
      { token: "operator", foreground: "556677" },
      { token: "identifier", foreground: "1a2232" },
      { token: "delimiter", foreground: "445566" },
    ],
    colors: {
      "editor.background": "#f0f4f8",
      "editor.foreground": "#1a2232",
      "editor.lineHighlightBackground": "#e4e9f0",
      "editor.selectionBackground": "#c8d8f0",
      "editorLineNumber.foreground": "#a8b4c8",
      "editorLineNumber.activeForeground": "#3a4f6a",
      "editorGutter.background": "#f0f4f8",
      "editorCursor.foreground": "#e85a1a",
      "editor.findMatchBackground": "#e85a1a44",
      "editorHoverWidget.background": "#e4e9f0",
      "editorHoverWidget.border": "#d93050",
    },
  },
};
