import type { ThemeDefinition } from "./index";

export const tokyoNightTheme: ThemeDefinition = {
  id: "tokyo-night",
  label: "Tokyo Night",
  base: "dark",
  swatch: "#7aa2f7",
  css: {
    "--bg-void": "#13141f",
    "--bg-deep": "#1a1b2e",
    "--bg-panel": "#1f2132",
    "--bg-surface": "#24283b",
    "--bg-elevated": "#2a2e42",
    "--bg-hover": "#313552",
    "--border-dim": "#1f2335",
    "--border-soft": "#292e42",
    "--border-mid": "#3b4261",
    "--text-primary": "#c0caf5",
    "--text-secondary": "#9aa5ce",
    "--text-muted": "#565f89",
    "--text-dim": "#3b3f5c",
    "--accent": "#7aa2f7",
    "--accent-glow": "rgba(122, 162, 247, 0.2)",
    "--accent-dim": "rgba(122, 162, 247, 0.08)",
    "--green": "#9ece6a",
    "--red": "#f7768e",
    "--yellow": "#e0af68",
    "--blue": "#7dcfff",
    "--error-bg": "rgba(247, 118, 142, 0.06)",
    "--error-bg-hint": "rgba(247, 118, 142, 0.06)",
    "--error-border": "rgba(247, 118, 142, 0.25)",
    "--statusbar-text": "rgba(255, 255, 255, 0.9)",
    "--statusbar-text-dim": "rgba(255, 255, 255, 0.7)",
    "--statusbar-badge-bg": "rgba(0, 0, 0, 0.2)",
  },
  monaco: {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "keyword", foreground: "bb9af7", fontStyle: "bold" },
      { token: "keyword.operator", foreground: "7dcfff" },
      { token: "type", foreground: "2ac3de" },
      { token: "support.function", foreground: "7dcfff" },
      { token: "constant", foreground: "ff9e64" },
      { token: "string", foreground: "9ece6a" },
      { token: "number", foreground: "ff9e64" },
      { token: "number.float", foreground: "ff9e64" },
      { token: "comment", foreground: "565f89", fontStyle: "italic" },
      { token: "operator", foreground: "89ddff" },
      { token: "identifier", foreground: "c0caf5" },
      { token: "delimiter", foreground: "737aa2" },
    ],
    colors: {
      "editor.background": "#1a1b2e",
      "editor.foreground": "#c0caf5",
      "editor.lineHighlightBackground": "#24283b",
      "editor.selectionBackground": "#2a2e42",
      "editorLineNumber.foreground": "#3b4261",
      "editorLineNumber.activeForeground": "#565f89",
      "editorGutter.background": "#1a1b2e",
      "editorCursor.foreground": "#7aa2f7",
      "editor.findMatchBackground": "#7aa2f744",
      "editorHoverWidget.background": "#1a1b2e",
      "editorHoverWidget.border": "#f7768e",
    },
  },
};
