import type { Monaco } from "@monaco-editor/react";
import type { IRange, languages } from "monaco-editor";

export const snippets = (monaco: Monaco, range: IRange): languages.CompletionItem[] => [
  {
    label: "algoritmo",
    kind: monaco.languages.CompletionItemKind.Snippet,
    insertText:
      'algoritmo "${1:NomeDoPrograma}"\n\nvar\n   ${2:variavel}: ${3|inteiro,real,caractere,logico|}\n\ninicio\n   ${4}\n\nfimalgoritmo',
    insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
    documentation: "Estrutura completa do algoritmo",
    range,
  },
  {
    label: "leia",
    kind: monaco.languages.CompletionItemKind.Snippet,
    insertText: "leia(${1:variavel})",
    insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
    documentation: "Comando de entrada de variavel",
    range,
  },
  {
    label: "escreva",
    kind: monaco.languages.CompletionItemKind.Snippet,
    insertText: "escreva(${1:variavel})",
    insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
    documentation: "Comando de saída",
    range,
  },
  {
    label: "escreval",
    kind: monaco.languages.CompletionItemKind.Snippet,
    insertText: "escreval(${1:variavel})",
    insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
    documentation: "Comando de saída com quebra de linha",
    range,
  },
  {
    label: "se...entao...fimse",
    kind: monaco.languages.CompletionItemKind.Snippet,
    insertText: "se ${1:condicao} entao\n   ${2}\nfimse",
    insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
    documentation: "Estrutura condicional",
    range,
  },
  {
    label: "se...senao...fimse",
    kind: monaco.languages.CompletionItemKind.Snippet,
    insertText: "se ${1:condicao} entao\n   ${2}\nsenao\n   ${3}\nfimse",
    insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
    documentation: "Condicional com alternativa",
    range,
  },
  {
    label: "para...fimpara",
    kind: monaco.languages.CompletionItemKind.Snippet,
    insertText: "para ${1:i} de ${2:1} ate ${3:10} faca\n   ${4}\nfimpara",
    insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
    documentation: "Laço para",
    range,
  },
  {
    label: "enquanto...fimenquanto",
    kind: monaco.languages.CompletionItemKind.Snippet,
    insertText: "enquanto ${1:condicao} faca\n   ${2}\nfimenquanto",
    insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
    documentation: "Laço enquanto",
    range,
  },
  {
    label: "repita...ate",
    kind: monaco.languages.CompletionItemKind.Snippet,
    insertText: "repita\n   ${1}\nate ${2:condicao}",
    insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
    documentation: "Laço repita",
    range,
  },
  {
    label: "repita...fimrepita",
    kind: monaco.languages.CompletionItemKind.Snippet,
    insertText: "repita\n   ${1}\n   interrompa\nfimrepita",
    insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
    documentation: "Laço repita (sai apenas por interrompa)",
    range,
  },
  {
    label: "escolha...fimescolha",
    kind: monaco.languages.CompletionItemKind.Snippet,
    insertText: "escolha (${1:variavel})\n   caso ${2:valor}\n      ${3}\n   outrocaso\n      ${4}\nfimescolha",
    insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
    documentation: "Estrutura de seleção múltipla",
    range,
  },
  {
    label: "procedimento",
    kind: monaco.languages.CompletionItemKind.Snippet,
    insertText: "procedimento ${1:NomeProcedimento}(${2:params})\nvar\n   ${3}\ninicio\n   ${4}\nfimprocedimento",
    insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
    documentation: "Declaração de procedimento",
    range,
  },
  {
    label: "funcao",
    kind: monaco.languages.CompletionItemKind.Snippet,
    insertText: "funcao ${1:NomeFuncao}(${2:params}): ${3|inteiro,real,caractere,logico|}\nvar\n   ${4}\ninicio\n   ${5}\n   retorne ${6}\nfimfuncao",
    insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
    documentation: "Declaração de função",
    range,
  },
];
